#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#define APP_BALANCE_DBG_LOG_COUNT 256U
#define APP_BALANCE_DBG_LOG_DIVIDER 2U

#define APP_INITIAL_LEFT_X_MM      (-36.0f)
#define APP_INITIAL_LEFT_Y_MM      (-80.0f)
#define APP_INITIAL_RIGHT_X_MM      36.0f
#define APP_INITIAL_RIGHT_Y_MM     (-80.0f)
#define APP_INITIAL_FT_SPEED       200U
#define APP_INITIAL_FT_ACC           0U
#define APP_INITIAL_LEFT_DM_KP    60.0f
#define APP_INITIAL_LEFT_DM_KD     0.60f
#define APP_INITIAL_LEFT_DM_T     -4.0f
#define APP_INITIAL_RIGHT_DM_KP   60.0f
#define APP_INITIAL_RIGHT_DM_KD    0.60f
#define APP_INITIAL_RIGHT_DM_T     4.0f

#define APP_JOINT_HOLD_DIVIDER     2U
#define APP_WHEEL_SEND_DIVIDER     5U
#define APP_WHEEL_ENABLE_FRAMES  100U
#define APP_LEG_ASSIST_DIVIDER    40U
#define APP_LEG_ASSIST_DT_S       (APP_CONTROL_DT_S * (float)APP_LEG_ASSIST_DIVIDER)
#define APP_LEG_ASSIST_SLEW_RAD_S  0.10f
#define APP_LEG_ASSIST_LEFT_SIGN    1.0f
#define APP_LEG_ASSIST_RIGHT_SIGN  (-1.0f)
#define APP_LEG_ASSIST_LEFT_DM_KP  80.0f
#define APP_LEG_ASSIST_LEFT_DM_KD   0.80f
#define APP_LEG_ASSIST_RIGHT_DM_KP  90.0f
#define APP_LEG_ASSIST_RIGHT_DM_KD  0.90f

#define APP_CONTROL_DT_S           0.0005f
#define APP_BALANCE_DT_S           (APP_CONTROL_DT_S * (float)APP_WHEEL_SEND_DIVIDER)
#define APP_BALANCE_INTEGRAL_LIMIT  0.0f
#define APP_BALANCE_PITCH_TRIM_DEG  0.0f
#define APP_WHEEL_RADIUS_MM       360.0f
#define APP_SPEED_OUTER_KP_DEG_PER_MM_S 0.0f
#define APP_SPEED_OUTER_MAX_DEG    0.0f
#define APP_POSITION_HOLD_KP_DEG_PER_MM 0.0f
#define APP_POSITION_HOLD_MAX_DEG  0.0f
#define APP_POSITION_HOLD_RELEASE_VX_MM_S 5.0f
#define APP_TARGET_PITCH_TOTAL_MAX_DEG 2.0f
#define APP_BALANCE_PITCH_PREDICT_MAX_S  0.010f
#define APP_BALANCE_DEADBAND_DEG    0.40f
#define APP_BALANCE_MIN_TORQUE      0.0f
#define APP_BALANCE_TORQUE_SLEW    40.0f
#define APP_BALANCE_WHEEL_MIT_KD    0.02f
#define APP_BALANCE_TILT_STOP_DEG  30.0f
#define APP_BALANCE_TORQUE_SIGN     1.0f
#define APP_BALANCE_WHEEL_STATE_SIGN 1.0f
#define APP_WHEEL_ZERO_TICKS      400U

#define APP_TUNE_AUTOSTART          1U
#define APP_TUNE_USE_LEG_ASSIST     0U
#define APP_TUNE_POSE_DELAY_MS   3000U
#define APP_TUNE_START_DELAY_MS  8000U
#define APP_TUNE_RUN_MS             0U
#define APP_TUNE_WHEEL_KP          0.120f
#define APP_TUNE_WHEEL_KI          0.0f
#define APP_TUNE_WHEEL_KD          0.250f
#define APP_TUNE_WHEEL_MAX         1.2f
#define APP_TUNE_LEG_KP           (-0.008f)
#define APP_TUNE_LEG_KD           (-0.0015f)
#define APP_TUNE_LEG_BIAS         (-0.035f)
#define APP_TUNE_LEG_MAX           0.10f

#define APP_COLD_START_HOLD_MS   3000U
#define APP_STARTUP_DISABLE_RETRY_MS 100U
#define APP_IMU_ACTIVATE_RETRY_MS  200U
#define APP_IMU_ACTIVE_STABLE_MS  1000U
#define APP_DM_ACTIVE_TIMEOUT_MS   300U
#define APP_AUTOSTART_MAX_GYRO_RAD_S 0.8f
#define APP_AUTOSTART_MAX_PITCH_DEG 25.0f
#define APP_AUTOSTART_MAX_ROLL_DEG  35.0f
#define APP_JOINT_ENABLE_RETRY_MS   100U
#define APP_JOINT_ENABLE_RETRY_WINDOW_MS 2000U
#define APP_FT_POSE_REFRESH_MS      200U
#define APP_FT_POSE_REFRESH_WINDOW_MS 4000U

#define APP_REMOTE_TIMEOUT_MS     500U
#define APP_REMOTE_MAX_VX_MM_S    300
#define APP_REMOTE_MAX_WZ_MRAD_S  800
#define APP_REMOTE_VX_SLEW_MM_S2  600.0f
#define APP_REMOTE_WZ_SLEW_MRAD_S2 1600.0f
#define APP_REMOTE_TURN_TORQUE_MAX 0.25f
#define APP_REMOTE_TURN_TORQUE_SIGN -1.0f
#define APP_REMOTE_RECOVERY_TILT_DEG 8.0f

#endif /* APP_CONFIG_H */
